LoggingApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basesites.urls', namespace = 'basesites')),
    path('users/', include('users.urls', namespace = 'users')),
    path('uploader/', include('uploader.urls', namespace = 'uploader')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

basesites/urls.py
from django.conf.urls import url 
from . import views

app_name = 'Logging application'

urlpatterns = [
    #main page
    url(r'^$', views.index, name = 'index'),

]

uploader/urls.py
from django.conf.urls import url 
from django.conf.urls.static import static
from django.conf import settings 
from django.urls import path
from . import views

app_name = 'uploader'

urlpatterns = [
    url(r'^fileupload/$', views.UploadFile, name = 'fileupload'),
    url(r'^filelist/$', views.file_list, name = 'filelist'),
    path('filelist/<int:pk>/', views.DeleteFile, name = 'deletefile'),
]

users/urls.py
from django.conf.urls import url 
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name ='users/login.html'), name = 'login'),
    url(r'^logout/$', views.logout_view, name = 'logout'),
    url(r'^register/$', views.register, name = 'register'),
]

basesites/models.py
from django.db import models

# Create your models here.

uploader/models.py
from django.db import models

# Create your models here.
class File(models.Model):
    name = models.CharField(max_length = 100)
    file = models.FileField(upload_to='files')

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

users/models.py
from django.db import models

# Create your models here.

uploader/forms.py
from django import forms
from .models import File

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('name', 'file')

basesites/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'basesites/index.html')

uploader/views.py
from django.shortcuts import redirect, render
from .models import File
from .forms import FileForm
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.views.generic import TemplateView

# Create your views here.

@login_required
def file_list(request):
    files = File.objects.all()
    return render(request, 'uploader/filelist.html', {'files': files})

@login_required
def UploadFile(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/uploader/filelist')
    else:
        form = FileForm()
    return render(request, 'uploader/fileupload.html', {'form': form})

@login_required
def DeleteFile(request, pk):
    if request.method == 'POST':
        file = File.objects.get(pk = pk)
        file.delete()
    return redirect('/uploader/filelist')
    
    

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('basesites:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username = new_user, password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('basesites:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

basesites/templates/basesites/base.html
{% load bootstrap3 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equip="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="generator" content="Jekyll v4.0.1">
        <title>Logging Application</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/navbar-static/">
        
</head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="LearningLogs:navbar-top.css" rel="stylesheet">
  </head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    {% if user.is_authenticated %}
        <a class="navbar-brand" href={% url 'basesites:index' %}>Logging Application</a>
    {% else %}
        <a class="navbar-brand" href={% url 'basesites:index' %}>Logging Application</a>
    {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item active"><a class="nav-link">Hello, {{ user.username }}.</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'uploader:fileupload' %}">Upload</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'uploader:filelist' %}">Download</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'users:register' %}">Sign Up</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'users:login' %}">Sign In</a></li>
                    {% endif %}
                </ul>
            </div>
    </nav>

    <div class="container">

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
    </body>
</html>

basesites/templates/basesites/index.html
{% extends "basesites/base.html" %}

{% block content %}
<h2>
    <a>Hello</a>
</h2>
{% endblock content %}

uploader/templates/uploader/filelist.html
{% extends "basesites/base.html" %}
{% load bootstrap3 %}

{% block header%}
    <h2>Files</h2>
{% endblock header%}

{% block content %}
    <table class="table">
        <thread>
            <tr>
                <th>Name</th>
                <th>Download</th>
                <th>Delete</th>
            </tr>
        </thread>
        <tbody>
            {% for file in files %}
                <tr>
                    <td>{{ file.name }}</td>
                    <td>
                        <a href="{{ file.file.url }}" class="btn btn-primary btn-sm">Download</a> 
                        {% comment %} <a href="https://www.youtube.com/watch?v=-15VC4Yxzys&feature=youtu.be&t=14" class="btn btn-primary btn-sm">Download</a> {% endcomment %}
                    </td>
                    <td>
                        <form method="post" action="{% url 'uploader:deletefile' file.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    
{% endblock content %}

uploader/templates/uploader/fileupload.html
{% extends "basesites/base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}

{% block header%}
    <h2>Upload file</h2>
{% endblock header%}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary btn-lg">Upload</button>
    </form>
{% endblock content %}

users/templates/users/login.html
{% extends "basesites/base.html" %}
{% load bootstrap3 %}

{% block header%}
    <h2>Signing in</h2>
{% endblock header%}

{% block content %}
    <form method="post" action="{% url 'users:login'%}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-outline-secondary">Zaloguj</button
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'uploader:filelist' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "basesites/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form method="post" action="{% url 'users:register'%}">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-secondary">Rejestruj</button
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'basesites:index' %}" />
    </form>
{% endblock content %}